service: kamal-inertia-shadcn-rails

image: railshobbyist/kamal-inertia-shadcn-rails

servers:
  web:
    - 78.47.103.193

proxy:
  ssl: true
  host: kamal-inertia-shadcn-rails.jhanas.club
  app_port: 3000

# Credentials for your image host.
registry:
  username: railshobbyist
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    DB_HOST: 192.168.0.2

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "kamal-inertia-shadcn-rails_storage:/storage/database.sqlite3"

# Configure the image builder.
builder:
  arch: amd64
