service: kamal-inertia-shadcn-rails

image: railshobbyist/kamal-inertia-shadcn-rails

servers:
  web:
    - 78.47.103.193
  vite_ssr:
    hosts:
      - 192.168.0.1
    cmd: bundle exec vite ssr
    options:
      network-alias: vite_ssr

proxy:
  ssl: true
  host: kamal-inertia-shadcn-rails.jhanas.club
  app_port: 3000

# Credentials for your image host.
registry:
  username: railshobbyist
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    # SOLID_QUEUE_IN_PUMA: true
    VITE_RUBY_HOST: "vite_ssr"
    DB_HOST: 192.168.0.2

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "kamal-inertia-shadcn-rails_storage:/storage/database.sqlite3"

asset_path: /vite

# Configure the image builder.
builder:
  arch: amd64
